language: ruby
rvm:
- 2.2.1


# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.

script:
- bundle exec jekyll build -d _site/sxarchipelagos
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --empty-alt-ignore


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler